# 定义订单服务
upstream order_service {
    server 127.0.0.1:8080 max_fails=3 fail_timeout=30s;
}

# 定义用户服务
upstream user_service {
    server 127.0.0.1:9090 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name 192.168.1.20;

    # 根据不同的 URL 路径路由到不同的本地服务名
    location /orders {
        proxy_pass http://order_service;
        proxy_next_upstream error timeout http_500; # 容错机制
    }

    location /users {
        proxy_pass http://user_service;
    }

    # 兜底配置
    location / {
        return 404 "No Internal Service Found for this path.";
    }
}