server {
    listen 80;
    server_name 192.168.1.11;# 这里可以继续使用 server_name 或者监听特定 IP

    location / {
        # 假设 Nginx C 的 IP 是 192.168.1.12
        proxy_pass http://192.168.1.12;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}