upstream backend_servers {
    server 127.0.0.1:8080;
    server 192.168.2.123:9090;
}

server {
    listen 80;
server_name 192.168.1.12;
    location / {
        proxy_pass http://backend_servers;
        
        # 基础超时设置，防止后端服务无响应导致链路卡死
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }
}